sudo: required

language: node

services:
  - docker
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get -qq update
  - rm -f /etc/default/docker
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce

script:
  - docker build -t d34th/cloud9-docker .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push d34th/cloud9-docker;
    fi
